name: ocr_batch_extractor
description: Flutter app for batch OCR extraction and cropping.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  archive: ^3.4.10
  image: ^4.1.7
  image_cropper: ^6.0.0
  google_mlkit_text_recognition: ^0.11.0
  path_provider: ^2.1.2
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true